import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'email_hint': 'Email',
          'app_name': 'Balochi Language App',
          'welcome_text': 'Hi there! I’m Balochi!',
          'welcome_long_text': "Learn languages whenever and wherever you want.", // It's free and forever.
          'welcome_btn1_text': "Create An Account", // "GET STARTED",
          'try_for_free': "Try a Free Lesson",
          'welcome_btn2_text': 'Sign In', // "I ALREADY HAVE AN ACCOUNT",
          'app_language_text': "What language you can speak?",
          'native_language': "Your Native Language",
          'hi_there_im_eL': "Hi there! I’m Kiri!",
          'indonesia': "Indonesia",
          'balochi': "Balochi",
          'change': "Change",
          'app_language': "App Language",
          'english': "English",
          'mandarin': "Mandarin",
          'spanish': "Spanish",
          'hindi': "Hindi",
          'french': "French",
          'continue': "Continue",
          'or_continue_with': "or continue with",
          'learn_language_text': "What Language would you like to learn?",
          'app_source_text': "How did you know about Balochi?",
          'tiktok': "Tiktok",
          'facebook': "Facebook",
          'google_search': "Google Search",
          'television': "Television",
          'app_store': "App Store",
          'language_knowledge_text': "How much English do you know?",
          'signal0': "I just started learning\nEnglish",
          'signal1': "I know some words\nand phrases",
          'signal2': "I can have a simple\nconversation",
          'signal3': "I'm at intermediate\nlevel or above",
          'language_study_reason_text': "Why are you studying English?",
          'language_study_reason1': "Just for fun",
          'language_study_reason2': "Improve my career",
          'language_study_reason3': "Support my education",
          'language_study_reason4': "Vacation preparation",
          'language_study_reason5': "Others reason",
          'course_achievements_text': "This is what you can\nachieve!",
          'course_achievements_point1': "Speak fluently and confidently",
          'course_achievements_point1.1': "40,000+ stress-free interactive exercises",
          'course_achievements_point2': "Mastering a lot of vocabulary",
          'course_achievements_point2.1': "2000+ practical words and phrases",
          'course_achievements_point3': "Cultivate study habits",
          'course_achievements_point3.1': "Smart reminders, fun challenges, and more",
          'daily_study_target_text': 'What is your daily study target?',
          'daily_study_target_p1': '5 mins / day',
          'daily_study_target_p1.1': 'Relax',
          'daily_study_target_p2': '10 mins / day',
          'daily_study_target_p2.1': 'Normal',
          'daily_study_target_p3': '15 mins / day',
          'daily_study_target_p3.1': 'Serious',
          'daily_study_target_p4': '30 mins / day',
          'daily_study_target_p4.1': 'Great',
          'daily_study_target_p5': '60 mins / day',
          'daily_study_target_p5.1': 'Awesome',
          'onboarding_complete_text': 'Awesome!',
          'What_language_for_learnKad?': "What language do\nyou want to use for\nBalochi?",
          'learn_languages_whenever': "Learn languages whenever and \nwherever you want. It's free and forever.",

          'onboarding_complete_text2':
              "Create a profile now so you can save\nprogress and connect with friends.\nOr you can skip it.",
          'create_profile': "CREATE PROFILE",
          'skip': "SKIP",
          // register screens
          'name_screen_text': "What is your name? 🧑 👩",
          'full_name': "Full Name",
          'age_screen_text': "How old are you? 🎂",
          'age': "Age",
          'email_screen_text': "What is your email \naddress? ✉️",
          'phone_screen_text': "What is your phone number? ✉️ ",
          'email': "Email",
          'phone': "Phone",
          "areYouSureYouWantToExit": "Do you want to exit the app?",
          "yes": "Yes",
          "no": "No",
          'password_screen_text': "Create a password 🔐",
          'password': "Password",
          'hurray': "Hurray!!",
          'welcome': "Welcome 👋",
          'profile_created': "Your profile has been created successfully.",
          'continue_to_home': "CONTINUE TO HOME",
          'login_screen_text': 'Let’s you in',
          'remember_me': 'Remember me',
          'forgot_password': 'Forgot Password?',
          'sign_in': 'Sign in',
          'login_privacy_policy_text': 'By Signing in you are agreeing to\nour ',
          'register_privacy_policy_text': 'By Signing up you are agreeing to\nour ',
          'privacy_policy': 'Terms and privacy policy',

          'sign_up': 'Sign up',
          'dont_have_account': 'Don’t have an account?',

          'forgot_password_page_text': 'Forgot Password 🔑',
          'forgot_password_page_text2': 'Enter your email address to get an OTP code to reset your password.',
          'forgot_password_get_otp': 'Enter your email address to get an OTP code to reset your password.',

          'otp_page_text': 'You’ve got mail 📩',
          'otp_page_text2':
              'We have sent the OTP verification code to your email address. Check your email and enter the code below.',
          'otp_page_text3': "Didn't receive email?",
          'otp_page_text4': "You can resend code in 55 s",
          'otp_page_text4_1': "Resend Code",
          'confirm': "Confirm",

          'new_password_page_text': "Create new password 🔐",
          'new_password_page_text2':
              "Save the new password in a safe place, if you forget it then you have to do a forgot password again.",
          'new_password_page_text3': "Create a new password",
          'new_password_page_text4': "Confirm a new password",

          'welcome_back': "Welcome back!",
          'reset_msg': "Your profile has been created successfully.",
          //home screens
          'en': 'EN',
          'challenges_day': 'Challenges (day)',
          'challenge_done': 'challenge done',
          'remaining': 'remaining',
          'days': 'days',
          'view': 'View',
          'challenges_calendar': 'Challenges Calendar',
          'start': 'START!',
          'lesson': 'Lesson',
          'forming_an_infinite_verb': 'Forming an infinite verb',
          'describing_abstract_objects': 'Describing abstract objects',

//navmenu diamonds page
          'you_have': 'You have',
          'diamonds': 'Diamonds',
          'diamonds_description': 'You can use diamonds to freeze & increase the time to complete the challenge.',
          'buy_more_diamonds': 'Buy More Diamonds',
          'promo_code': 'Promo Code',

          'redeem_promo_code': 'Redeem promo code',
          'enter_promo_code': 'Enter promo code to get free diamonds.',
          'redeem_now': 'Redeem now',
          'power_up': 'Power-up',
          'time_enhancer': 'Time enhancer',
          'paypal': 'PayPal',
          'google_pay': 'Google Pay',
          'apple_pay': 'Apple Pay',
          'bank_card': 'Bank Card',
          'sub_title': 'Powered by stripe',
          'select_payment_method': 'Select payment method',
          'payment_method': 'Payment Method',
          'review_summary': 'Review Summary',
          'confirm_payment': 'Confirm Payment',
          'complete_payment_text1': 'Yeaayy!!',
          'successful': 'Successful!',
          'ok': 'OK',
          'discount': 'Discount',
          'price': 'Price',
          'total_payment': 'Total Payment',
          'payment': 'Payment',
          'complete_payment_text2': 'diamonds have been added to your account.',
          // lesson pages

          'loading': 'Loading...',
          'lesson_loading_text': 'Complete the course faster to get more XP and Diamonds.',
          'translate_this_sentence': 'Translate this sentence',
          'check_answers': 'Check Answers',
          'check': 'Check',
          'correct': 'Correct!',
          'correct_answer': 'Correct Answer:',
          'wrong': 'Wrong!!',

          'speak_this_sentence': 'Speak this sentence',
          'cannot_talk_now': "Can't talk now",
          'tap_to_talk': "Tap to talk",
          'what_does_this_sentence_mean': "What does this sentence mean?",
          'what_does_audio_say': "What does the audio say?",
          'tap_to_play_audio': "Tap to play audio",
          'stop_audio': "Stop audio",
          'stop': "Stop",
          'tap_the_matching_word_pair': "Tap the matching word pair",
          'time': "Time",
          'get': "Get",
          'xp': "XP",
          'total': "Total",
          'complete': "Complete",
          'challenge': "Challenge",
          'share': "Share",
          'great': "Great",
          'oK_great': "OK, Great!",
          'payment_successful': "Payment Successful!",
          'perfect_lessons': "Perfect Lessons",
          'accuracy': "Accuracy",
          'daily_mission_updates': "Daily mission updates!",
          'rank_page_text': "Cool! Your rank goes up!",
          'days_straight': "days straight!",
          'lesson_completed': "Lesson completed!",
          'days_straight_screen_text': "Increases if you practice every day and will return to zero if you skip a day!",

          //leader board screens

          'leaderboard': 'Leaderboard',
          'joined_since': 'Joined since',
          'follow': 'Follow',
          'edit_profile': 'Edit Profile',
          'following': 'Following',
          'followers': 'Followers',
          'lifetime': 'Lifetime',
          'message': 'Message',

          //leader board screens

          'target': 'Target',
          'badges': 'Badges',
          'daily_missions': 'Daily Missions',
          'challenge_events': 'Challenge Events',
          'competition': 'Competition',
          'Kiri_match': 'Kiri Match!',
          'days_left': 'days left',
          'take_the_challenge': 'Take the Challenge',
          'challenge_events_text': 'Earn 2000 XP and get a special bonus from Kiri!',

          'quiz_king': 'Quiz King',
          'quiz': 'Quiz',
          'compass_smart': 'Compass Smart',
          'diamond_winner': 'Diamond Winner',
          'shining_star': 'Shining Star',
          'most_active': 'Most Active',
          'the_sweetest': 'The Sweetest',
          'best_target': 'Best Target',
          'quick_fix': 'Quick Fix',
          'the_fastest_man': 'The Fastest Man',
          'smart_learning': 'Smart Learning',
          'this_year': 'This Year',

          'premium': 'Premium',
          'premium_screen_text': 'Go Premium and enjoy the benefits!',
          'premium_benefits_text': 'Go Premium and enjoy the benefits! 🔥',
          'go_premium_now': 'Go Premium Now',
          'no_thanks': 'No, Thanks',
          'benefit1': 'Unlimited Diamonds',
          'benefit1.1': 'Get unlimited diamonds to make the learning process easier.',
          'benefit2': 'Lessons Reminder',
          'benefit2.1': 'Time reminder feature to study, so you never miss it.',
          'benefit3': 'Learning Calendar',
          'benefit3.1': 'The learning calendar feature makes it more organized.',
          'benefit4': 'Boost Your XP',
          'benefit4.1': 'Get more XP with premium subscription.',
          'benefit5': 'Learning Ebook',
          'benefit5.1': 'Bonus learning ebook so you can read it anytime.',
          'benefit6': 'Learn Better',
          'benefit6.1': 'Better and complete modules for the learning process.',
          'benefit7': 'No Waiting Time',
          'benefit7.1': 'Learn fast with no waiting time or delay.',
          'benefit8': 'Free and No Ads',
          'benefit8.1': 'Ad-free and hassle-free with a premium subscription.',
          'choose_plan': 'Choose a subscription plan',
          'month': 'Month',
          'get_over': 'Get over',
          'off': 'off',
          'close': 'Close',
          'cannot_memorize_words?': 'Quick Memorizing',
          'word': 'Word',
          'unlock': 'Unlock',
          'update_notifications': 'Update Notifications',
          'update_accessibility': 'Update Accessibility',
          'update': 'Update',
          'update_notifications?': 'Are you sure you want to update the notifications?',
          'are_you_sure_update_accessibility?': 'Are you sure you want to update the accessibility?',
          'sorry_incorrect': 'Sorry, Incorrect',
          'choose_correct_answer_from_below_choices': 'Choose correct answer from below\nchoices',
          'move_the_word_to_the_correct_answer': 'Move the word to the correct\nanswer',
          'competition_with_friends': 'Competitions with friends',
          'competition_with_friends_text1':
              'Avoid mistakes in order to get maximum points for the round and become the first among your competitors',
          'confirm_your_identity': 'Confirm your identity',
          'confirmation_dialog_text': 'A verification code has been sent to your email. Please confirm your identity.',
          'update_profile': 'Update Profile',
          // course screens
          'description': 'Description',
          'training_and_tutorials': 'Training & Tutorials',
          'learn': 'Learn',
          'gold_certified': 'Gold Certified',
          'language': 'Language',
          'course': 'Course',
          'schedule': 'Schedule',
          'view_appointments': 'View Appointments',
          'appointment': 'Appointment',
          'create_new_course': 'Create a New Course',
          'new': 'New',
          'date': 'Date',
          'create': 'Create',
          'title': 'Title',
          'instructor': 'Instructor',

          'hello': 'Hello',
          'test': 'Test',
          'translation': 'Translation',
          'oral': 'Oral',
          'courses': 'Courses',
          'more': 'More',
          'download': 'Download',
          'certificate': 'Certificate',
          'details': 'Details',
          'list': 'List',
          'speaker': 'Speaker',
          'speak_now': 'Speak Now',
          'listening': 'Listening... ',
          'chapter': 'Chapter',
          'basic': 'Basic',
          'resume': 'Resume',
          'from': 'From',
          'last': 'Last',
          'search': 'Search',
          'congratulation': 'Congratulation',
          'here': 'Here',
          'completed': 'Completed',
          'kiri_message': 'Hello, I am Kiri, Your Language Assistant',

          'internet_exception': "We're unable tp show results.\nPlease check your data\nconnection.",
          'general_exception': "We're unable to process your request.\n Please try again",
          // 'welcome_back': 'Welcome\nBack',
          'login': 'Login',
          'password_hint': 'Password',
          'accessibility': 'Accessibility',
          'notifications': 'Notifications',
          'find_friends': 'Find Friends',
          'more_courses': 'More Courses',
          'student_profile': 'Student Profile',
          'check_it': "Check it",
          'create_your_account': 'Create Your Account',
          'chat_bot': 'Chat Bot',
        },
        'ur_PK': {'email_hint': 'asدسسدفاسف'},
      };
}
