// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZZK2ezObGCObmYyfcxrRCgJa_AJzQc4',
    appId: '1:976605774309:android:48b5779219c35414286f0c',
    messagingSenderId: '976605774309',
    projectId: 'balochi-tutor',
    storageBucket: 'balochi-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBixS9UPApWMRFEM3WK5oCbO5W28cacUHQ',
    appId: '1:976605774309:ios:ec7e64ef9778e4ae286f0c',
    messagingSenderId: '976605774309',
    projectId: 'balochi-tutor',
    storageBucket: 'balochi-tutor.firebasestorage.app',
    androidClientId: '976605774309-thpsf5v6agqt4v1vnvbdgsu4bbpjet8o.apps.googleusercontent.com',
    iosClientId: '976605774309-pe02c9562ie552sqe02u5volt5dcjg2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.balochiTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBixS9UPApWMRFEM3WK5oCbO5W28cacUHQ',
    appId: '1:976605774309:ios:ec7e64ef9778e4ae286f0c',
    messagingSenderId: '976605774309',
    projectId: 'balochi-tutor',
    storageBucket: 'balochi-tutor.firebasestorage.app',
    androidClientId: '976605774309-thpsf5v6agqt4v1vnvbdgsu4bbpjet8o.apps.googleusercontent.com',
    iosClientId: '976605774309-pe02c9562ie552sqe02u5volt5dcjg2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.balochiTutor',
  );
}
